config/routes.rb
Rails.application.routes.draw do

	# StartsController
	root 'starts#index'
	get 'privacy', to: 'starts#privacy'
	get 'contact', to: 'starts#contact'
	get 'pricing', to: 'starts#pricing'

	# UsersController
	get 'login', to: 'users#login'
	post 'login', to: 'users#login_action'
	get 'login_implicit', to: 'users#login_implicit'
   post 'login_implicit', to: 'users#login_implicit_action'
   get 'login_session', to: 'users#login_session'
   post 'login_session', to: 'users#login_session_action'
	get 'logout', to: 'users#logout'
	get 'signup', to: 'users#signup'
	post 'signup', to: 'users#signup_action'
	get 'user', to: 'users#show'
	post 'user', to: 'users#update'
	get 'redirect', to: 'users#redirect'

	get 'password_reset', to: 'users#password_reset'
	post 'password_reset', to: 'users#password_reset_action'
	get 'reset_password/:password_confirmation_token', to: 'users#reset_password', as: 'reset_password'
	post 'reset_password/:password_confirmation_token', to: 'users#reset_password_action'
	get 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user', as: 'confirm_user'
	post 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user_action'
	get 'change_email/:id/:email_confirmation_token', to: 'users#change_email'
	get 'change_password/:id/:password_confirmation_token', to: 'users#change_password'
	get 'reset_new_email/:id', to: 'users#reset_new_email'
	get 'delete_account/:id/:email_confirmation_token/:password_confirmation_token', to: 'users#delete_account'

	# AppsController
	get 'apps', to: 'apps#index'

	# DevsController
	get 'dev', to: 'devs#index'
	post 'dev', to: 'devs#create_app'
	get 'dev/general', to: 'devs#general', as: 'show_general'
	post 'dev/general', to: 'devs#set_general_period'
	get 'dev/:id', to: 'devs#show', as: 'show_app'
	post 'dev/:id', to: 'devs#create_table'
	get 'dev/:id/table/:name', to: 'devs#show_table', as: 'show_table'
	get 'dev/:id/event/:name', to: 'devs#show_event', as: 'show_event'
	post 'dev/:id/event/:name', to: 'devs#set_event_period'
	get 'dev/:id/general', to: 'devs#general_app', as: 'show_general_app'
	post 'dev/:id/general', to: 'devs#set_general_app_period'
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController

	before_action :require_user

	def index
		begin
			@dev = Dav::Dev.get(session[:jwt])
		rescue StandardError => e
			puts e.message
			flash[:danger] = "There was an error: " + e.message
			redirect_to root_path
		end
	end

	def create_app
		name = params[:name]
		description = params[:description]

		begin
			app = Dav::App.create(session[:jwt], name, description)
			redirect_to dev_path
		rescue StandardError => e
			puts replace_error_message(e.message)
			flash[:danger] = replace_error_message(e.message)
			redirect_to dev_path
		end
	end

	def general
		begin
			@users = Dav::Analytics.get_users(session[:jwt])["users"]
			@plan_count = Hash.new

			@confirmed_users_count = Hash.new
			@confirmed_users_count["Confirmed"] = 0
			@confirmed_users_count["Unconfirmed"] = 0

			@users.each do |user|
				if user["confirmed"]
					@confirmed_users_count["Confirmed"] += 1
				else
					@confirmed_users_count["Unconfirmed"] += 1
				end
			end

			# Sort for the users chart
			default_period = 10 * 365 * 24 * 60 * 60		# 10 years
			sort_by = params["sort_by"]
			period = params["period"] ? params["period"].to_i : default_period

			sorted_arrays = count_time_cumulatively(period, sort_by, @users, "created_at")
			@sorted_array = sorted_arrays[0]

			# Set the plan count
			@plan_count["Free"] = 0
			@plan_count["Plus"] = 0
			@plan_count["Pro"] = 0
			
			@users.each do |user|
				case user["plan"]
				when 1
					@plan_count["Plus"] += 1
				when 2
					@plan_count["Pro"] += 1
				else
					@plan_count["Free"] += 1
				end
			end

			@new_users_count = sorted_arrays[1].count

			# @active_users_count data type: Array<Hash<name: string, data: Hash<string, int>>>
			active_users = Dav::Analytics.get_active_users(session[:jwt], Time.now.to_i - period)
			@active_users_count = [
				{ "name" => "Daily", "data" => Hash.new },
				{ "name" => "Monthly", "data" => Hash.new },
				{ "name" => "Yearly", "data" => Hash.new }
			]

			active_users.each do |active_user|
				# Get the daily active users
				@active_users_count[0]["data"][active_user.time] = active_user.count_daily
				@active_users_count[1]["data"][active_user.time] = active_user.count_monthly
				@active_users_count[2]["data"][active_user.time] = active_user.count_yearly
			end

			@current_active_users_count = Hash.new
			@current_active_users_count["Daily"] = active_users.size > 0 ? active_users.last.count_daily : 0
			@current_active_users_count["Monthly"] = active_users.size > 0 ? active_users.last.count_monthly : 0
			@current_active_users_count["Yearly"] = active_users.size > 0 ? active_users.last.count_yearly : 0
		rescue StandardError => e
			puts e.message
			flash[:danger] = "There was an error: " + e.message
			redirect_to root_path
		end
	end

	def set_general_period
		period_length = params[:period].to_i
		period_format = params[:period_format]
		sort_by = params[:sort_by]

		period = convert_period_to_timestamp(period_format, period_length)

		redirect_to show_general_path(sort_by: sort_by, period: period)
	end

	def show
		@app = Dav::App.get(session[:jwt], params[:id])
	end

	def create_table
		name = params[:name]

		begin
			table = Dav::Table.create(session[:jwt], name, params[:id])
			redirect_to show_app_path(params[:id])
		rescue StandardError => e
			puts replace_error_message(e.message)
			flash[:danger] = replace_error_message(e.message)
			redirect_to show_app_path(params[:id])
		end
	end

	def show_table
		@table = Dav::Table.get(session[:jwt], params[:id], params[:name])
	end

	def show_event
		default_period = 60 * 60 * 24 * 30	# Ca. one month
		sort_by = params["sort_by"].to_s.empty? ? "day" : params["sort_by"]
		period = params["period"] ? params["period"] : default_period
		period_start = Time.now - period.to_i

		@event = Dav::Event.get_by_name(session[:jwt], params[:name], params[:id], sort_by, period_start.strftime("%s"))

		@sorted_date_logs = Hash.new
		@sorted_data_logs = Hash.new
		event_logs = Array.new

		# Remove all logs that are outside the period
		@event.logs.each do |log|
			log_date = DateTime.parse(log.time)

			if log_date > period_start
				event_logs.push(log)
			end
		end

		if event_logs.count == 0
			return
		end

		# Set every entry between the first date and the last date to 0
		start_date = DateTime.parse(event_logs.first.time)
		end_date = DateTime.parse(event_logs.last.time)

		if sort_by == "year"
			RailsDateRange(start_date..end_date).every(years: 1).each do |log|
				@sorted_date_logs[format_year(log)] = 0
			end

			@sorted_date_logs[format_year(start_date)] = 0
			@sorted_date_logs[format_year(end_date)] = 0
		elsif sort_by == "month"
			RailsDateRange(start_date..end_date).every(months: 1).each do |log|
				@sorted_date_logs[format_month(log)] = 0
			end

			@sorted_date_logs[format_month(start_date)] = 0
			@sorted_date_logs[format_month(end_date)] = 0
		elsif sort_by == "hour"
			RailsDateRange(start_date..end_date).every(hours: 1).each do |log|
				@sorted_date_logs[format_hour(log)] = 0
			end

			@sorted_date_logs[format_hour(start_date)] = 0
			@sorted_date_logs[format_hour(end_date)] = 0
		else	# Sort by day
			RailsDateRange(start_date..end_date).every(days: 1).each do |log|
				@sorted_date_logs[format_day(log)] = 0
			end

			@sorted_date_logs[format_day(start_date)] = 0
			@sorted_date_logs[format_day(end_date)] = 0
		end

		@countries = Hash.new
		@browser_with_version = Hash.new
		@browser_without_version = Hash.new
		@os_with_version = Hash.new
		@os_without_version = Hash.new
		@chrome_versions = Hash.new
		@firefox_versions = Hash.new
		@edge_versions = Hash.new
		@windows_versions = Hash.new
		@android_versions = Hash.new

		event_logs.each do |log|
			# Get the date
			log_date = DateTime.parse(log.time)

			if sort_by == "year"
				date = format_year(log_date)
			elsif sort_by == "month"
				date = format_month(log_date)
			elsif sort_by == "hour"
				date = format_hour(log_date)
			else	# Sort_by == day
				date = format_day(log_date)
			end

			@sorted_date_logs[date] = @sorted_date_logs[date] + log.total

			# Get the country
			country = get_property_counts_by_name(log.properties, "country").first
			if country
				@countries[country["value"]] ? @countries[country["value"]] += country["count"] : @countries[country["value"]] = country["count"]
			end

			# Get the browser
			browser_names = get_property_counts_by_name(log.properties, "browser_name")
			browser_versions = get_property_counts_by_name(log.properties, "browser_version")
			
			i = 0
			browser_names.each do |browser_name_hash|
				browser_name = browser_name_hash["value"]
				browser_version = browser_versions[i]["value"]
				name = "#{browser_name} #{browser_version}"
				count = browser_names[i]["count"]

				# Increase the count of the browser in @browser_without_version
				@browser_without_version[browser_name] ? @browser_without_version[browser_name] += count : @browser_without_version[browser_name] = count

				# Increase the count of the browser in @browser_with_version
				@browser_with_version[name] ? @browser_with_version[name] += count : @browser_with_version[name] = count

				# Increase the count of the specific browser
				if browser_name.include? "Chrome"
					# @chrome_versions
					@chrome_versions[name] ? @chrome_versions[name] += count : @chrome_versions[name] = count
				elsif browser_name.include? "Firefox"
					# @firefox_versions
					@firefox_versions[name] ? @firefox_versions[name] += count : @firefox_versions[name] = count
				elsif browser_name.include? "Edge"
					# @edge_versions
					@edge_versions[name] ? @edge_versions[name] = @edge_versions[name] += count : @edge_versions[name] = count
				end

				i += 1
			end

			# Get the os
			i = 0
			log.properties.each do |property|
				if property["name"] == "os_name"
					# Increase the count of the os in @os_without_version
					count = property["count"]
					name = property["value"]
					@os_without_version[name] ? @os_without_version[name] += count : @os_without_version[name] = count

					if log.properties[i + 1] && log.properties[i + 1]["name"] == "os_version"
						# Increase the count of the os in @os_with_version
						name = "#{property["value"]} #{log.properties[i + 1]["value"]}"
						@os_with_version[name] ? @os_with_version[name] += count : @os_with_version[name] = count

						# Increase the count of the specific os
						if name.include? "Windows"
							# @windows_versions
							@windows_versions[name] ? @windows_versions[name] += count : @windows_versions[name] = count
						elsif name.include? "Android"
							# @android_versions
							@android_versions[name] ? @android_versions[name] += count : @android_versions[name] = count
						end
					end
				end

				i += 1
			end
		end
	end

	def set_event_period
		period_length = params[:period].to_i
		period_format = params[:period_format]
		sort_by = params[:sort_by]

		period = convert_period_to_timestamp(period_format, period_length)

		redirect_to show_event_path(sort_by: sort_by, period: period)
	end

	def general_app
		begin
			@app = Dav::App.get(session[:jwt], params[:id])
			@analytics = Dav::Analytics.get_app(session[:jwt], params[:id])

			# Sort for the users chart
			default_period = 10 * 365 * 24 * 60 * 60		# 10 years
			sort_by = params["sort_by"]
			period = params["period"] ? params["period"].to_i : default_period

			sorted_arrays = count_time_cumulatively(period, sort_by, @analytics["users"], "started_using")

			@sorted_time = sorted_arrays[0]
			@new_users_count = sorted_arrays[1].count
			@total_users_count = @analytics["users"].count


app/views/devs/general.html.erb
<div class="container content">
   <h1 class="text-center">
		<%= link_to dev_path, class: "btn", style: "background-color: transparent; color: black" do %>
			<%= fa_icon "arrow-left", style: "font-size: 20px;" %>
		<% end %>
		General information
	</h1>

   <h3 align="center" class="my-4">Users</h3>
   <%= area_chart @sorted_array %>

	<p class="font-weight-light mt-3 mb-0">New users: <%= @new_users_count %></p>
	<p class="font-weight-light">Total users: <%= @users.count %></p>

	<div class="row mt-4">
		<div class="col-4">
			<h5>Sort by</h5>
			<div class="list-group mt-4">
				<%= link_to "Hour", show_general_path(sort_by: "hour", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Day", show_general_path(sort_by: "day", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Month", show_general_path(sort_by: "month", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Year", show_general_path(sort_by: "year", period: params[:period]), class: "list-group-item list-group-item-action" %>
			</div>
		</div>

		<div class="col-6 offset-2">
			<h5>Period</h5>
			<%= form_tag(show_general_path, class: "form-horizontal mt-4", method: "post", role: "form") do |f| %>
				<div class="form-group row">
					<div class="col-6">
						<%= number_field_tag :period, nil, class: "form-control" %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-6">
						<%= select_tag :period_format, options_for_select(['Hours', 'Days', 'Weeks', 'Months', 'Years'], 'Weeks') %>
						<br>
						<%= hidden_field_tag :sort_by, params[:sort_by] %>
						<%= submit_tag("Update", class: "btn btn-primary btn-md mt-4") %>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-12 col-md-6">
   		<h3 align="center" class="my-5">Plans</h3>
   		<%= pie_chart @plan_count %>
		</div>

		<div class="col-12 col-md-6">
			<h3 align="center" class="my-5">User confirmations</h3>
   		<%= pie_chart @confirmed_users_count %>
		</div>
	</div>
	
	<h3 align="center" class="my-5">Active Users</h3>
	<%= line_chart @active_users_count %>
	
	<div class="row mt-5">
		<div class="col-md-8 offset-md-2">
			<%= column_chart @current_active_users_count %>
		</div>
	</div>
</div>

app/views/devs/general_app.html.erb
<div class="container content">
   <h1 class="text-center">
		<%= link_to show_app_path(@app.id), class: "btn", style: "background-color: transparent; color: black" do %>
			<%= fa_icon "arrow-left", style: "font-size: 20px;" %>
		<% end %>
		<%= @app.name %>
	</h1>

   <h3 align="center" class="my-4">Users</h3>
   <%= area_chart @sorted_time %>

	<p class="font-weight-light mt-3 mb-0">New users: <%= @new_users_count %></p>
	<p class="font-weight-light">Total users: <%= @total_users_count %></p>

   <div class="row mt-4">
		<div class="col-4">
			<h5>Sort by</h5>
			<div class="list-group mt-4">
				<%= link_to "Hour", show_general_app_path(sort_by: "hour", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Day", show_general_app_path(sort_by: "day", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Month", show_general_app_path(sort_by: "month", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Year", show_general_app_path(sort_by: "year", period: params[:period]), class: "list-group-item list-group-item-action" %>
			</div>
		</div>

		<div class="col-6 offset-2">
			<h5>Period</h5>
			<%= form_tag(show_general_app_path, class: "form-horizontal mt-4", method: "post", role: "form") do |f| %>
				<div class="form-group row">
					<div class="col-6">
						<%= number_field_tag :period, nil, class: "form-control" %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-6">
						<%= select_tag :period_format, options_for_select(['Hours', 'Days', 'Weeks', 'Months', 'Years'], 'Weeks') %>
						<br>
						<%= hidden_field_tag :sort_by, params[:sort_by] %>
						<%= submit_tag("Update", class: "btn btn-primary btn-md mt-4") %>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	<h3 align="center" class="my-5">Active Users</h3>
	<%= line_chart @active_users_count %>

	<div class="row mt-5">
		<div class="col-md-8 offset-md-2">
			<%= column_chart @current_active_users_count %>
		</div>
	</div>
</div>

app/views/devs/index.html.erb
<div class="container content">
   <h1 class="d-flex justify-content-center">Your Apps</h1>

   <div class="row justify-content-center mt-4">
      <% @dev.apps.each do |app| %>
         <div class="card bg-light mb-3 col-12" style="max-width: 20rem; margin: 5px">
            <%= link_to show_app_path(app.id), class: "no-link-deco text-dark" do %>
               <div class="card-body row">
                  <h4 class="card-title mx-auto my-2"><%= app.name %></h4>
               </div>
            <% end %>
         </div>
      <% end %>

      <div class="card bg-light mb-3 col-12" style="max-width: 20rem; margin: 5px" data-toggle="modal" data-target="#create-app-modal">
         <div class="card-body row">
            <h2 class="card-title mx-auto">+</h2>
         </div>
      </div>
   </div>

   <div class="d-flex justify-content-center">
      <%= link_to "General information", show_general_path, class: "btn btn-secondary mt-3" %>
   </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="create-app-modal">
  	<div class="modal-dialog" role="document">
    	<div class="modal-content">
      	<div class="modal-header">
        		<h5 class="modal-title">Create new App</h5>
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
        		</button>
			</div>
			<%= form_tag(dev_path, class: "form-horizontal", method: "post", role: "form") do |f| %>
      		<div class="modal-body">
					<div class="form-group col-10 offset-1">
						<%= label_tag :name, "Name", class: "col-sm-2 col-form-label" %>
						<div class="col-sm-10">
							<%= text_field_tag :name, nil, class: "form-control", placeholder: "Name" %>
						</div>
               </div>
               <div class="form-group col-10 offset-1">
                  <%= label_tag :description, "Description", class: "col-sm-2 col-form-label" %>
                  <div class="col-sm-10">
                     <%= text_field_tag :description, nil, class: "form-control", placeholder: "Description" %>
                  </div>
               </div>
      		</div>
				<div class="modal-footer">
					<%= submit_tag("Create", class: "btn btn-primary") %>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			<% end %>
    	</div>
  	</div>
</div>

app/views/devs/show.html.erb
<div class="container content">
   <h1 align="center">
		<%= link_to dev_path, class: "btn", style: "background-color: transparent; color: black" do %>
			<%= fa_icon "arrow-left", style: "font-size: 20px;" %>
		<% end %>
		<%= @app.name %>
	</h1>

   <h2 class="mt-3">Tables</h2>
   <div class="list-group">
		<% @app.tables.each do |table| %>
			<%= link_to table.name, show_table_path(name: table.name), class: "list-group-item list-group-item-action text-dark" %>
		<% end %>
		<p class="list-group-item list-group-item-action" style="font-weight: bold;" data-toggle="modal" data-target="#create-table-modal">+</p>
   </div>

	<!-- Events -->
	<h2 class="mt-3">Events</h2>
	<% @app.events.each do |event| %>
		<%= link_to event.name, show_event_path(name: event.name), class: "list-group-item list-group-item-action text-dark" %>
	<% end %>

	<%= link_to "General information", show_general_app_path, class: "btn btn-secondary mx-auto mt-3" %>
</div>



<div class="modal fade" tabindex="-1" role="dialog" id="create-table-modal">
  	<div class="modal-dialog" role="document">
    	<div class="modal-content">
      	<div class="modal-header">
        		<h5 class="modal-title">Create new table</h5>
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
        		</button>
			</div>
			<%= form_tag(show_app_path(params[:id]), class: "form-horizontal", method: "post", role: "form") do |f| %>
      		<div class="modal-body">
					<div class="form-group col-10 offset-1">
						<%= label_tag :name, "Name", class: "col-sm-2 col-form-label" %>
						<div class="col-sm-10">
							<%= text_field_tag :name, nil, class: "form-control", placeholder: "Name" %>
						</div>
					</div>
      		</div>
				<div class="modal-footer">
					<%= submit_tag("Create", class: "btn btn-primary") %>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			<% end %>
    	</div>
  	</div>
</div>

app/views/devs/show_event.html.erb
<div class="container content">
   <h1 class="text-center">
		<%= link_to show_app_path(params[:id]), class: "btn", style: "background-color: transparent; color: black" do %>
			<%= fa_icon "arrow-left", style: "font-size: 20px;" %>
		<% end %>
		<%= @event.name %>
	</h1>

   <%= area_chart @sorted_date_logs %>
	<%= geo_chart @countries %>

	<div class="row d-flex justify-content-center">
		<% if @browser_with_version %>
			<div class="my-5">
				<h3 class="text-center">Browser with version</h3>
				<%= pie_chart @browser_with_version %>
			</div>
		<% end %>

		<% if @browser_without_version %>
			<div class="my-5">
				<h3 class="text-center">Browser</h3>
				<%= pie_chart @browser_without_version %>
			</div>
		<% end %>

		<% if @os_with_version %>
			<div class="my-5">
				<h3 class="text-center">Operating systems with version</h3>
				<%= pie_chart @os_with_version %>
			</div>
		<% end %>

		<% if @os_without_version %>
			<div class="my-5">
				<h3 class="text-center">Operating systems</h3>
				<%= pie_chart @os_without_version %>
			</div>
		<% end %>

		<% if @chrome_versions %>
			<div class="my-5">
				<h3 class="text-center">Chrome versions</h3>
				<%= pie_chart @chrome_versions %>
			</div>
		<% end %>

		<% if @firefox_versions %>
			<div class="my-5">
				<h3 class="text-center">Firefox versions</h3>
				<%= pie_chart @firefox_versions %>
			</div>
		<% end %>

		<% if @edge_versions %>
			<div class="my-5">
				<h3 class="text-center">Microsoft Edge versions</h3>
				<%= pie_chart @edge_versions %>
			</div>
		<% end %>

		<% if @windows_versions %>
			<div class="my-5">
				<h3 class="text-center">Windows versions</h3>
				<%= pie_chart @windows_versions %>
			</div>
		<% end %>

		<% if @android_versions %>
			<div class="my-5">
				<h3 class="text-center">Android versions</h3>
				<%= pie_chart @android_versions %>
			</div>
		<% end %>
	</div>

   <div class="row mt-4">
		<div class="col-4">
			<h5>Sort by</h5>
			<div class="list-group mt-4">
				<%= link_to "Hour", show_event_path(params[:id], params[:name], sort_by: "hour", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Day", show_event_path(params[:id], params[:name], sort_by: "day", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Month", show_event_path(params[:id], params[:name], sort_by: "month", period: params[:period]), class: "list-group-item list-group-item-action" %>
				<%= link_to "Year", show_event_path(params[:id], params[:name], sort_by: "year", period: params[:period]), class: "list-group-item list-group-item-action" %>
			</div>
		</div>

		<div class="col-6 offset-2">
			<h5>Period</h5>
			<%= form_tag(show_event_path, class: "form-horizontal mt-4", method: "post", role: "form") do |f| %>
				<div class="form-group row">
					<div class="col-6">
						<%= number_field_tag :period, nil, class: "form-control" %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-6">
						<%= select_tag :period_format, options_for_select(['Hours', 'Days', 'Weeks', 'Months', 'Years'], 'Weeks') %>
						<br>
						<%= hidden_field_tag :sort_by, params[:sort_by] %>
						<%= submit_tag("Update", class: "btn btn-primary btn-md mt-4") %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/devs/show_table.html.erb
<div class="container content">
   <h1 align="center">
      <%= link_to show_app_path(params[:id]), class: "btn", style: "background-color: transparent; color: black" do %>
			<%= fa_icon "arrow-left", style: "font-size: 20px;" %>
		<% end %>
      <%= @table.name %>
   </h1>
</div>