config/routes.rb
Rails.application.routes.draw do

	# StartsController
	root 'starts#index'
	get 'privacy', to: 'starts#privacy'
	get 'contact', to: 'starts#contact'
	get 'pricing', to: 'starts#pricing'

	# UsersController
	get 'login', to: 'users#login'
	post 'login', to: 'users#login_action'
	get 'login_implicit', to: 'users#login_implicit'
   post 'login_implicit', to: 'users#login_implicit_action'
   get 'login_session', to: 'users#login_session'
   post 'login_session', to: 'users#login_session_action'
	get 'logout', to: 'users#logout'
	get 'signup', to: 'users#signup'
	post 'signup', to: 'users#signup_action'
	get 'user', to: 'users#show'
	post 'user', to: 'users#update'
	get 'redirect', to: 'users#redirect'

	get 'password_reset', to: 'users#password_reset'
	post 'password_reset', to: 'users#password_reset_action'
	get 'reset_password/:password_confirmation_token', to: 'users#reset_password', as: 'reset_password'
	post 'reset_password/:password_confirmation_token', to: 'users#reset_password_action'
	get 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user', as: 'confirm_user'
	post 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user_action'
	get 'change_email/:id/:email_confirmation_token', to: 'users#change_email'
	get 'change_password/:id/:password_confirmation_token', to: 'users#change_password'
	get 'reset_new_email/:id', to: 'users#reset_new_email'
	get 'delete_account/:id/:email_confirmation_token/:password_confirmation_token', to: 'users#delete_account'

	# AppsController
	get 'apps', to: 'apps#index'

	# DevsController
	get 'dev', to: 'devs#index'
	post 'dev', to: 'devs#create_app'
	get 'dev/general', to: 'devs#general', as: 'show_general'
	post 'dev/general', to: 'devs#set_general_period'
	get 'dev/:id', to: 'devs#show', as: 'show_app'
	post 'dev/:id', to: 'devs#create_table'
	get 'dev/:id/table/:name', to: 'devs#show_table', as: 'show_table'
	get 'dev/:id/event/:name', to: 'devs#show_event', as: 'show_event'
	post 'dev/:id/event/:name', to: 'devs#set_event_period'
	get 'dev/:id/general', to: 'devs#general_app', as: 'show_general_app'
	post 'dev/:id/general', to: 'devs#set_general_app_period'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :require_user, only: [:show]

   def login
		if params[:redirect]
			session[:redirect] = params[:redirect]
      end
      
      if logged_in?
         # Redirect to root or the redirect path
         redirect = params[:redirect] ? params[:redirect] : ""
         redirect_to root_path + redirect
      end
   end

	def login_action
      email = params[:email]
      password = params[:password]
		auth = get_auth_object

      begin
         user = auth.login(email, password)
         set_session(user)
         
			log("login")

			redirect = ""
			if session[:redirect]
            redirect = session[:redirect]
            session[:redirect] = nil
			end

			redirect_to root_path + redirect
      rescue StandardError => e
         flash.now[:danger] = replace_error_message(e.message)
         render 'login'
      end
   end

   def login_implicit
      api_key = params[:api_key]
		redirect_url = params[:redirect_url]
      auth = get_auth_object

      if !api_key || !redirect_url
         flash[:danger] = "There was an error. Please try again."
         redirect_to root_path
      else
         if session[:jwt]
            @user = Dav::User.get_by_jwt(session[:jwt])
         end

         session[:api_key] = api_key
			session[:redirect_url] = redirect_url
      end
   end

   def login_implicit_action
      api_key = session[:api_key]
		redirect_url = session[:redirect_url]

      email = params[:email]
		password = params[:password]
      
      if params[:current_user]
         # Logged in user was clicked, redirect to app
         # Check if the user is logged in on the website
         begin
            user = Dav::Auth.login_by_jwt(session[:jwt], api_key)

				session[:api_key] = nil
				session[:redirect_url] = nil
            log("login_implicit")
            
            redirect_to redirect_path(operation: "login", redirect_url: "#{redirect_url}?jwt=#{user.jwt}")
         rescue StandardError => e
				flash[:danger] = replace_error_message(e.message)
				redirect_to login_implicit_path + "?api_key=#{api_key}&redirect_url=#{CGI.escape(redirect_url)}"
         end
      else
         # Another user has logged in
         begin
            auth = get_auth_object

            user = auth.login(email, password)
            set_session(user)
   
            dev = Dav::Dev.get_by_api_key(auth, api_key)
            dev_auth = Dav::Auth.new(api_key: dev.api_key, 
                                    secret_key: dev.secret_key,
                                    uuid: dev.uuid,
                                    environment: Rails.env)
            user2 = dev_auth.login(email, password)
   
            session[:api_key] = nil
				session[:redirect_url] = nil
				log("login_implicit")
				
				redirect_to redirect_path(operation: "login", redirect_url: "#{redirect_url}?jwt=#{user2.jwt}")
         rescue StandardError => e
            flash[:danger] = replace_error_message(e.message)
				redirect_to login_implicit_path + "?api_key=#{api_key}&redirect_url=#{CGI.escape(redirect_url)}"
         end
      end
	end
	
	def login_session
		api_key = params[:api_key]
		app_id = params[:app_id]
      redirect_url = params[:redirect_url]

		if !api_key || !app_id || !redirect_url
			flash[:danger] = "There was an error. Please try again."
         redirect_to root_path
		else
			# Save the params in the session
			session[:api_key] = api_key
			session[:app_id] = app_id
			session[:redirect_url] = redirect_url

			# Device info
			client = DeviceDetector.new(request.user_agent)
			session[:device_name] = client.device_name || "Unknown"
			session[:device_type] = client.device_type.nil? ? "Unknown" : client.device_type.capitalize
			session[:device_os] = "#{client.os_name} #{client.os_full_version}"
		end
	end

	def login_session_action
		email = params[:email]
		password = params[:password]
		api_key = session[:api_key]
		app_id = session[:app_id]
		redirect_url = session[:redirect_url]
		device_name = session[:device_name]
		device_type = session[:device_type]
		device_os = session[:device_os]
      auth = get_auth_object
		
		begin
			result = Dav::Session.create(auth.get_token, email, password, api_key, app_id, device_name, device_type, device_os)

			# Clear the session variables
			session[:api_key] = nil
			session[:redirect_url] = nil
			session[:app_id] = nil
			session[:device_name] = nil
			session[:device_type] = nil
			session[:device_os] = nil
			log("login_session")

			redirect_to redirect_path(operation: "login", redirect_url: "#{redirect_url}?jwt=#{result.jwt}")
		rescue StandardError => e
			flash[:danger] = replace_error_message(e.message)
			redirect_to login_session_path(api_key: api_key, app_id: app_id, redirect_url: redirect_url)
		end
	end

   def logout
      clear_session
      flash[:success] = "You are now logged out. Have a nice day :)"
      redirect_to root_path
   end

   def signup
      if logged_in? && !params[:redirect_url]
         redirect_to root_path
      end

      session[:redirect_url] = params[:redirect_url]
      session[:app_id] = params[:app_id]
      session[:api_key] = params[:api_key]
   end

   def signup_action
      username = params[:username]
      email = params[:email]
      password = params[:password]
      password_confirmation = params[:password_confirmation]
		auth = get_auth_object
		redirect_url = session[:redirect_url]
		app_id = session[:app_id]
		api_key = session[:api_key]
      
		# Clear the session variables
		session[:redirect_url] = nil
		session[:app_id] = nil
		session[:api_key] = nil

      begin
			if password == password_confirmation
				
				if app_id && api_key
					client = DeviceDetector.new(request.user_agent)
					device_name = client.device_name || "Unknown"
					device_type = client.device_type.nil? ? "Unknown" : client.device_type.capitalize
					device_os = "#{client.os_name} #{client.os_full_version}"

					user = auth.signup_with_session(email, password, username, app_id, api_key, device_name, device_type, device_os)
					log("signup_session")
				else
					user = auth.signup(email, password, username)
					log("signup")
				end

				set_session(user)
            new_redirect_url = "#{redirect_url}?jwt=#{user.jwt}"
				redirect_to redirect_path(operation: "signup", redirect_url: redirect_url ? new_redirect_url : root_path)
         else
				flash[:danger] = "The password confirmation does not match your password."
				redirect_to signup_path(redirect_url: redirect_url, app_id: app_id, api_key: api_key)
         end
      rescue StandardError => e
         flash[:danger] = replace_error_message(e.message)
			redirect_to signup_path(redirect_url: redirect_url, app_id: app_id, api_key: api_key)
      end
   end

   def show
		@user = Dav::User.get(session[:jwt], session[:user_id])
		@avatar_url = ENV["DAV_BLOB_STORAGE_BASE_URL"] + @user.id.to_s + ".png"

		@archives = Array.new
		@user.archives.each do |archive|
			@archives.push(Dav::Archive.get(@user.jwt, archive.id))
		end
   end

   def update
      auth = get_auth_object
      @user = Dav::User.get(session[:jwt], session[:user_id])
      username = params[:username]
      email = params[:email]
      password = params[:password]
      password_confirmation = params[:password_confirmation]
      app_id = params[:app_id]
      avatar = params[:avatar]
      delete_account = params[:delete_account]
      create_archive = params[:create_archive]
		archive_id = params[:archive_id]
		update_payment_info = params[:update_payment_info]
		upgrade_plus = params[:upgrade_plus]
		upgrade_pro = params[:upgrade_pro]
		downgrade_free = params[:downgrade_free]
		downgrade_plus = params[:downgrade_plus]
		resend_confirmation_email = params[:resend_confirmation_email]
		
      if username
         if username == @user.username
            redirect_to user_path
         elsif username.length < 1
            redirect_to user_path
         else
            # Update username
            begin
               @user.update({username: username})
               flash[:success] = "Your new username was saved successfully!"
            rescue StandardError => e
               flash[:danger] = replace_error_message(e.message)
				end
				redirect_to user_path
         end
      end

      if email
         if email == @user.email
            redirect_to user_path
         elsif email.length < 1
            redirect_to user_path
         else
            # Update email
            begin
               @user.update({email: email})
               flash[:success] = "We sent you an email to your new email address to confirm it."
            rescue StandardError => e
               flash[:danger] = replace_error_message(e.message)
				end
				redirect_to user_path
         end
      end

      if password || password_confirmation
         if password.length < 1 && password_confirmation.length < 1
            redirect_to user_path
         elsif password.length < 5
            flash[:danger] = "Your new password is too short."
            redirect_to user_path
         elsif password != password_confirmation
            flash[:danger] = "Your new password does not match your password confirmation."
            redirect_to user_path
         else
            # Update password
            begin
               @user.update({password: password})
               flash[:success] = "You will receive an email to confirm your new password."
            rescue StandardError => e
               flash[:danger] = replace_error_message(e.message)
				end
				redirect_to user_path
         end
      end

      if app_id
         # Remove app data
         begin

app/views/users/confirm_user.html.erb
<div class="content container">
   <h1 align="center">Confirm your email</h1>
	<p align="center">Please enter your password to confirm your email address.</p>
	<%= render 'layouts/messages' %>

   <%= form_tag(confirm_user_path, class: "form-horizontal row mt-4", method: "post", role: "form") do |f| %>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
				<%= submit_tag("Send", class: "btn btn-primary btn-md mt-3") %>
         </div>
      </div>
   <% end %>
</div>

app/views/users/login.html.erb
<div class="content container">
   <h1 align="center">Log in</h1>
   <%= render 'layouts/messages' %>

   <%= form_tag(login_path, class: "form-horizontal row mt-4", method: "post", role: "form") do |f| %>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :email, "Email", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= email_field_tag :email, nil, class: "form-control", placeholder: "Email" %>
         </div>
      </div>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
            <p class="mt-2"><%= link_to "Forgot password", password_reset_path, style: "color: black; font-size: 15px;" %></p>
            <%= submit_tag("Log in", class: "btn btn-primary btn-md") %>
         </div>
      </div>
   <% end %>
</div>

app/views/users/login_implicit.html.erb
<div class="content container">
   <h1 align="center">Log in</h1>
   <%= render 'layouts/messages' %>

   <p hidden id="logged-in"><%= !session[:jwt].nil? %></p>

   <% if session[:jwt] %>
      <div class="list-group col-sm-6 offset-sm-3 col-md-4 offset-md-4">
         <div id="logged-in-user-list">
            <%= button_to(login_implicit_path, params: {current_user: true}, type: 'button', class: "list-group-item list-group-item-action") do %>
               <div class="media">
                  <div class="media-left">
                     <%= image_tag(@user.avatar, class: "media-object", height: "70px") %>
                  </div>
                  <div class="media-body mt-3 ml-3">
                     <h4 class="media-heading"><%= @user.username %></h4>
                  </div>
               </div>
            <% end %>
            
            <div class="list-group-item list-group-item-action" id="log-in-user">
               <div class="media">
                  <div class="media-left ml-3">
                     <%= fa_icon "user-plus", style: "font-size: 45px" %>
                  </div>
                  <div class="media-body mt-3 ml-3">
                     <h6 class="media-heading">Log in as another user</h6>
                  </div>
               </div>
            </div>
         </div>
      </div>
   <% end %>

   <%= form_tag(login_implicit_path, class: "form-horizontal mt-4", method: "post", role: "form") do |f| %>
      <div class="hidden" id="login-implicit-form">
         <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
            <%= label_tag :email, "Email", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
               <%= email_field_tag :email, nil, class: "form-control", placeholder: "Email" %>
            </div>
         </div>
         <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
            <%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
               <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
               <p class="mt-2"><%= link_to "Forgot password", password_reset_path, style: "color: black; font-size: 15px;" %></p>
               <%= submit_tag("Log in", class: "btn btn-primary btn-md") %>
               <%= link_to "Sign up", signup_path(redirect_url: session[:redirect_url]), class: "btn btn-secondary btn-md", style: "float: right;" %>
            </div>
         </div>
      </div>
   <% end %>
</div>

app/views/users/login_session.html.erb
<div class="content container mt-4">
   <h1 align="center">Log in</h1>
   <%= render 'layouts/messages' %>

	<%= form_tag(login_session_path, class: "form-horizontal mt-4", method: "post", role: "form") do |f| %>
		<!-- Email field -->
		<div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
			<%= label_tag :email, "Email", class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">
				<%= email_field_tag :email, nil, class: "form-control", placeholder: "Email" %>
			</div>
		</div>

		<!-- Password field -->
		<div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
			<%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
			<div class="col-sm-10">
				<%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
				<%= submit_tag("Log in", class: "btn btn-primary btn-md mt-3") %>
				<%= link_to "Sign up", signup_path(redirect_url: session[:redirect_url], app_id: session[:app_id], api_key: session[:api_key]), class: "btn btn-secondary btn-md mt-3", style: "float: right;" %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/password_reset.html.erb
<div class="content container">
   <h1 align="center">Reset your password</h1>
   <p align="center">Enter the email address of your account.</p>
   <%= render 'layouts/messages' %>

   <%= form_tag(password_reset_path, class: "form-horizontal row mt-4", method: "post", role: "form") do |f| %>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :email, "Email", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= email_field_tag :email, nil, class: "form-control", placeholder: "Enter your email" %>
            <%= submit_tag("Send", class: "btn btn-primary btn-md mt-3") %>
         </div>
      </div>
   <% end %>
</div>

app/views/users/redirect.html.erb
<div class="content container">
	<div class="row message">
		<div class="col-xs-10 col-xs-offset-1" style="min-width: 300px;">
			<div class='alert alert-success'>
				<%= content_tag :div, @message, :id => "flash_success" %>
			</div>
		</div>
	</div>
</div>

app/views/users/reset_password.html.erb
<div class="content container">
   <h1 align="center">Enter your new password</h1>
   <%= render 'layouts/messages' %>

   <%= form_tag(reset_password_path, class: "form-horizontal row mt-4", method: "post", role: "form") do |f| %>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
         </div>
      </div>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password_confirmation, "Password confirmation", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password_confirmation, nil, class: "form-control", placeholder: "Confirm your password" %>
            <%= submit_tag("Save", class: "btn btn-primary btn-md mt-3") %>
         </div>
      </div>
   <% end %>
</div>

app/views/users/signup.html.erb
<div class="content container">
   <h1 align="center">Sign up</h1>
   <%= render 'layouts/messages' %>

   <%= form_tag(signup_path, class: "form-horizontal row mt-4", role: "form", method: "post") do |f| %>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :username, "Username", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= text_field_tag :username, nil, class: "form-control", placeholder: "Your username" %>
         </div>
      </div>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :email, "Email", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= email_field_tag :email, nil, class: "form-control", placeholder: "Your email" %>
         </div>
      </div>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password, "Password", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password, nil, class: "form-control", placeholder: "Your password" %>
         </div>
      </div>
      <div class="form-group row col-sm-10 offset-sm-1 col-lg-8 offset-lg-2">
         <%= label_tag :password_confirmation, "Password confirmation", class: "col-sm-2 col-form-label" %>
         <div class="col-sm-10">
            <%= password_field_tag :password_confirmation, nil, class: "form-control", placeholder: "Confirm your password" %>
            <%= submit_tag("Sign up", class: "btn btn-primary btn-md mt-4") %>
         </div>
      </div>
   <% end %>
</div>