config/routes.rb
Rails.application.routes.draw do

	# StartsController
	root 'starts#index'
	get 'privacy', to: 'starts#privacy'
	get 'contact', to: 'starts#contact'
	get 'pricing', to: 'starts#pricing'

	# UsersController
	get 'login', to: 'users#login'
	post 'login', to: 'users#login_action'
	get 'login_implicit', to: 'users#login_implicit'
   post 'login_implicit', to: 'users#login_implicit_action'
   get 'login_session', to: 'users#login_session'
   post 'login_session', to: 'users#login_session_action'
	get 'logout', to: 'users#logout'
	get 'signup', to: 'users#signup'
	post 'signup', to: 'users#signup_action'
	get 'user', to: 'users#show'
	post 'user', to: 'users#update'
	get 'redirect', to: 'users#redirect'

	get 'password_reset', to: 'users#password_reset'
	post 'password_reset', to: 'users#password_reset_action'
	get 'reset_password/:password_confirmation_token', to: 'users#reset_password', as: 'reset_password'
	post 'reset_password/:password_confirmation_token', to: 'users#reset_password_action'
	get 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user', as: 'confirm_user'
	post 'confirm_user/:id/:email_confirmation_token', to: 'users#confirm_user_action'
	get 'change_email/:id/:email_confirmation_token', to: 'users#change_email'
	get 'change_password/:id/:password_confirmation_token', to: 'users#change_password'
	get 'reset_new_email/:id', to: 'users#reset_new_email'
	get 'delete_account/:id/:email_confirmation_token/:password_confirmation_token', to: 'users#delete_account'

	# AppsController
	get 'apps', to: 'apps#index'

	# DevsController
	get 'dev', to: 'devs#index'
	post 'dev', to: 'devs#create_app'
	get 'dev/general', to: 'devs#general', as: 'show_general'
	post 'dev/general', to: 'devs#set_general_period'
	get 'dev/:id', to: 'devs#show', as: 'show_app'
	post 'dev/:id', to: 'devs#create_table'
	get 'dev/:id/table/:name', to: 'devs#show_table', as: 'show_table'
	get 'dev/:id/event/:name', to: 'devs#show_event', as: 'show_event'
	post 'dev/:id/event/:name', to: 'devs#set_event_period'
	get 'dev/:id/general', to: 'devs#general_app', as: 'show_general_app'
	post 'dev/:id/general', to: 'devs#set_general_app_period'
end

app/views/layouts/_footer.html.erb
<div class="container">
   <footer class="footer">
      <small>
         Copyright &copy; 2019 by dav.
         All rights reserved
      </small>
      <nav>
         <ul>
            <li><%= link_to "Blog", "https://blog.dav-apps.tech", target: "blank", style: "color: black" %></li>
            <li><%= link_to "Twitter", "https://www.twitter.com/dav_apps", target: "blank", style: "color: black" %></li>
            <li><%= link_to "Contact", contact_path, style: "color: black" %></li>
            <li><%= link_to "Privacy Policy", privacy_path, style: "color: black" %></li>
            <li><%= link_to "v#{ENV['VERSION_NUMBER']}", "https://github.com/Dav2070/dav-apps/releases", target: "blank", style: "color: black" %></li>
         </ul>
      </nav>
   </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row message">
   <div class="col-xs-10 col-xs-offset-1" style="min-width: 300px;">
      <% flash.each do |name, msg| %>
         <div class='alert alert-<%="#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
         </div>
      <% end %>
   </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light fixed-top" id="mainNav">
   <div class="container fixed-top">
      <%= link_to "dav", root_path, class: "navbar-brand ml-3", id: "navbar-brand" %>
      <button class="navbar-toggler navbar-toggler-right mr-3" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarResponsive">
         <ul id="navbar-list" class="navbar-nav ml-auto">
            <% if session[:jwt] %>

            <!-- Logged in -->
            <li class="nav-item">
               <%= link_to "All Apps", apps_path, class: "nav-link navigation-text" %>
            </li>
            <li class="nav-item">
               <%= link_to session[:username], user_path, class: "nav-link navigation-text" %>
            </li>
            <li class="nav-item">
               <%= link_to "Log out", logout_path, class: "nav-link navigation-text" %>
            </li>

            <% else %>

            <!-- Not Logged in -->
            <li class="nav-item">
               <%= link_to "Pricing", pricing_path, class: "nav-link navigation-text" %>
            </li>
            <li class="nav-item">
               <%= link_to "Log in", login_path, class: "nav-link navigation-text" %>
            </li>
            <li class="nav-item">
               <%= link_to "Sign up", signup_path, class: "nav-link navigation-text" %>
            </li>
            <% end %>
         </ul>
      </div>
   </div>
</nav>

<%= javascript_include_tag "scripts/navbar.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
		<title>dav</title>
		<link rel='icon' type='image/x-icon' href='/favicon.ico' />
    	<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
		<meta name="google-site-verification" content="fFIzOijbIKAX0tm6IeBrqmSzIrrsD5q6kmnVbcdLpc8" />

    	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
		<%= javascript_include_tag "//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js" %>
		<%= stylesheet_link_tag "//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.light.min.css" %>
  	</head>

	<body>
		<%= render 'layouts/navbar' if show_navbar_and_footer(controller_name, action_name, params) %>
		<%= yield %>
		<%= render 'layouts/footer' if show_navbar_and_footer(controller_name, action_name, params) %>

		<% log_visit %>
		<script async defer src="https://cdn.simpleanalytics.io/hello.js"></script> 
		<noscript><img src="https://api.simpleanalytics.io/hello.gif" alt=""></noscript>
  	</body>
</html>